import type { Metadata } from "next";
import { Playfair_Display, Sarabun } from "next/font/google";
import "./globals.css";

const playfair = Playfair_Display({
  subsets: ['latin'],
  variable: '--font-playfair-display',
  display: 'swap'
})

const sarabun = Sarabun({
  subsets: ['latin'],
  variable: '--font-sarabun-display',
  display: 'swap',
  weight: "300"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sarabun.variable} ${playfair.variable} font-inter antialiased`}>
        {children}
      </body>
    </html>
  );
}
